package com.example.servingwebcontent.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.ID
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.ACCOUNT_ID
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.NAME
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.TOKEN
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.GMT_CREAT
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private Long gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.GMT_MODIFIED
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.BIO
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER01.AVATAR_URL
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.ID
     *
     * @return the value of USER01.ID
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.ID
     *
     * @param id the value for USER01.ID
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.ACCOUNT_ID
     *
     * @return the value of USER01.ACCOUNT_ID
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.ACCOUNT_ID
     *
     * @param accountId the value for USER01.ACCOUNT_ID
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.NAME
     *
     * @return the value of USER01.NAME
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.NAME
     *
     * @param name the value for USER01.NAME
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.TOKEN
     *
     * @return the value of USER01.TOKEN
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.TOKEN
     *
     * @param token the value for USER01.TOKEN
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.GMT_CREAT
     *
     * @return the value of USER01.GMT_CREAT
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public Long getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.GMT_CREAT
     *
     * @param gmtCreat the value for USER01.GMT_CREAT
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setGmtCreat(Long gmtCreat) {
        this.gmtCreat = gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.GMT_MODIFIED
     *
     * @return the value of USER01.GMT_MODIFIED
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.GMT_MODIFIED
     *
     * @param gmtModified the value for USER01.GMT_MODIFIED
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.BIO
     *
     * @return the value of USER01.BIO
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.BIO
     *
     * @param bio the value for USER01.BIO
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER01.AVATAR_URL
     *
     * @return the value of USER01.AVATAR_URL
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER01.AVATAR_URL
     *
     * @param avatarUrl the value for USER01.AVATAR_URL
     *
     * @mbg.generated Thu Jun 15 14:40:14 CST 2023
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}